apiVersion: v1
kind: Template
metadata:
  name: "apicast-validator-policies"
message: "APIcast Validator Policies"
objects:

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/display-name: AMP APIcast
    labels:
      app: apicast
    name: amp-apicast
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/display-name: AMP APIcast (latest)
      from:
        kind: ImageStreamTag
        name: ${AMP_RELEASE}
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
    - annotations:
        openshift.io/display-name: AMP APIcast ${AMP_RELEASE}
      from:
        kind: DockerImage
        name: ${AMP_APICAST_IMAGE}
      generation: null
      importPolicy:
        insecure: true
      name: ${AMP_RELEASE}
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""

- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
      app: apicast
    name: apicast-validator-policy

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: apicast
    name: apicast-validator-policy
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: apicast-validator-policy:latest
    source:
      git:
        uri: https://github.com/mayorova/apicast-example-policy.git
        ref: 'test'
      type: Git
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'amp-apicast:${AMP_RELEASE}'

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: apicast
    name: apicast-custom-policies
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 'amp-apicast:latest'
    postCommit:
      args:
        - '--test'
        - '--lazy'
      command:
        - bin/apicast
    resources: {}
    runPolicy: Serial
    source:
      images:
        - from:
            kind: ImageStreamTag
            name: 'apicast-validator-policy:latest'
          paths:
            # copy policy source code into the new image
            - destinationDir: policies
              sourcePath: /opt/app-root/policies/validinput
            # copy also installed dependencies to the policy folder, so they are vendored
            # - destinationDir: policies/validinput/0.1/resty/
            #   sourcePath: /opt/app-root/src/lua_modules/share/lua/5.1/resty/iputils.lua
      type: Dockerfile
      dockerfile: |
        FROM scratch
        COPY . src

    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: 'amp-apicast:${AMP_RELEASE}'
      type: Docker
    triggers:
      - type: ConfigChange
      - type: ImageChange

parameters:
- name: AMP_APICAST_IMAGE
  required: true
  value: registry.redhat.io/3scale-amp26/apicast-gateway
- name: AMP_RELEASE
  required: true
  description: AMP Version (e.g. 2.6)
  value: "2.6"
